### ISSUE TITLE
Directory exclusion

### ISSUE THREAD

**Issue by Ariesdragon** [EzeeLinux/xbt-external_backup_tool#10]
On added feature would be to excluded directories.  On my initial backup it copied the .trash directory which should be excluded from the backup.  I like the fact the symbolic links are not followed because the bulk of my data is on other drives that are shared with my Windows installation.  But the option to add exclusions to the initial backup would be a bonus.

**Comment by martinshields** [comment]
This is one of the reasons I stop using xbt . Would be nice to have exclusions.

**Comment by EzeeLinux** [comment]
The idea behind XBT is to make an enact snapshot of the /home directory. The program is designed that way... The restore function won't work properly if exclusions are made during backups, even things like the trash. :)

**Comment by martinshields** [comment]
Np . Found other alternatives.

Martin
