### ISSUE TITLE
Exit codes from command line/script

### ISSUE THREAD

**Issue by papa-smurph** [EzeeLinux/xbt-external_backup_tool#13]
When XBT is called from the command line and fails, it exits into the menu. This is can issue with running from scripts or a front end. (I am trying build by own GUI front end)

The "correct" behaviour should, when it is run from the command line and fails, it exits with a error code.

I have added this feature in my fork of XBT alongside a ton of other things. So it is possible.
However I don't know if you want it to have this behaviour.

**Comment by EzeeLinux** [comment]
I prefer the program to exit to a menu. That is how I want it to run. If you'd like to change it to fit your fork that's fine but I will leave the original as is. :)
