### ISSUE TITLE
[Suggestion] Samba integration

### ISSUE THREAD

**Issue by RaitaroH** [EzeeLinux/xbt-external_backup_tool#4]
I have an old laptop I use for backups. I ended up using this script for that.

For example:
```
sudo mount -t cifs //hp/Hp_home /media/raitaro/Hp_home -o user=raitaro,ip=####

sudo rsync -aH --info=progress2 /home/ \
/media/"$USER"/Hp_home/XBT_Backups/Dell_home 2>> /tmp/backup.log
```

And it works perfectly. I did not bother to add automount to fstab. But one can even do that.

**Comment by RaitaroH** [comment]
To be clear, if one needs this sorta thing then I think is not that hard to add. I simply followed the arch wiki to mount samba and then used rsync. 
It is just and idea you can play around with if you want.

**Comment by EzeeLinux** [comment]
It's an interesting idea but outside the scope of the program. The idea behind XBT is to make a copy of the local machine's /home directory. That's it. If you want to construct an rsnyc command to pull files over a network then that's fine but not for XBT. :)
